CREATE OR REPLACE PROCEDURE P_SEARCH_BOARD
(
	S_DAY NOTICE_BOARD.DAY%TYPE,
	S_MAX NOTICE_BOARD.MAX%TYPE,
	S_CONCEPT NOTICE_BOARD.CONCEPT%TYPE,
	RES OUT SYS_REFCURSOR
)
IS
BEGIN
	OPEN RES FOR SELECT * from notice_board where day= S_DAY and max = S_MAX and concept=S_CONCEPT ;
END P_SEARCH_BOARD;
/

VAR RET REFCURSOR;
EXEC P_SEARCH_BOARD('20/08/13', 12,0,:RET);
PRINT RET;