--모델 ID 중복 체크
CREATE OR REPLACE PROCEDURE M_IDCHECK
(
	MID MODEL.M_ID%TYPE,
	RES OUT NUMBER
)
IS
BEGIN
	SELECT COUNT(*) INTO RES FROM MODEL WHERE M_ID = MID;
END M_IDCHECK;
/

VAR RET NUMBER;
EXEC M_IDCHECK('ma',:RET);
PRINT RET;

--사진사 ID 중복 체크
CREATE OR REPLACE PROCEDURE P_IDCHECK
(
	PID PHOTOGRAPHER.P_ID%TYPE,
	RES OUT NUMBER
)
IS
BEGIN
	SELECT COUNT(*)  INTO RES FROM PHOTOGRAPHER WHERE P_ID = PID;
END P_IDCHECK;
/

VAR RET2 NUMBER;
EXEC P_IDCHECK('pa',:RET2);
PRINT RET2;
