CREATE OR REPLACE PROCEDURE P_MYPAGE
(
	PID NOTICE_BOARD.P_ID%TYPE,
	RES OUT SYS_REFCURSOR
)
IS
BEGIN
	OPEN RES FOR SELECT * FROM NOTICE_BOARD WHERE P_ID = PID;
END P_MYPAGE;
/

VAR RET REFCURSOR;
EXEC P_MYPAGE('ID1',:RET);
PRINT RET;