CREATE OR REPLACE PROCEDURE BOARD_ALL
(
	RES OUT SYS_REFCURSOR
)
IS
BEGIN
	OPEN RES FOR SELECT * FROM NOTICE_BOARD WHERE PROGRESS = 0;
END BOARD_ALL;
/

CREATE OR REPLACE PROCEDURE M_MYPAGE(
MID RESERVATION.M_ID%TYPE,
RES OUT SYS_REFCURSOR
)
IS
BEGIN
OPEN RES FOR SELECT* FROM RESERVATION WHERE M_ID=MID;
END;
/	

CREATE OR REPLACE PROCEDURE P_MYPAGE
(
	PID NOTICE_BOARD.P_ID%TYPE,
	RES OUT SYS_REFCURSOR
)
IS
BEGIN
	OPEN RES FOR SELECT * FROM NOTICE_BOARD WHERE P_ID = PID;
END P_MYPAGE;
/

CREATE OR REPLACE PROCEDURE RESERVATION_SPRAY
(
	SEQ RESERVATION.BRD_SEQ%TYPE,
	RES OUT SYS_REFCURSOR
)
IS
BEGIN
	OPEN RES FOR SELECT * FROM RESERVATION WHERE BRD_SEQ = SEQ;
END RESERVATION_SPRAY;
/

CREATE OR REPLACE PROCEDURE ADMIN_MODEL_LIST
(
	RES OUT SYS_REFCURSOR
)
IS
BEGIN
	OPEN RES FOR SELECT * FROM MODEL;
END ADMIN_MODEL_LIST;
/

CREATE OR REPLACE PROCEDURE ADMIN_PHOTOGRAPHER_LIST
(
	RES OUT SYS_REFCURSOR
)
IS
BEGIN
	OPEN RES FOR SELECT * FROM PHOTOGRAPHER;
END ADMIN_PHOTOGRAPHER_LIST;
/

CREATE OR REPLACE PROCEDURE ADMIN_BOARD_ALL
(
	RES OUT SYS_REFCURSOR
)
IS
BEGIN
	OPEN RES FOR SELECT * FROM NOTICE_BOARD;
END ADMIN_BOARD_ALL;
/

CREATE OR REPLACE PROCEDURE BOARD_ONE
(
	SEQ NOTICE_BOARD.BRD_SEQ%TYPE,
	RES OUT SYS_REFCURSOR
)
IS
BEGIN
	OPEN RES FOR SELECT * FROM NOTICE_BOARD WHERE BRD_SEQ = SEQ;
END BOARD_ONE;
/

CREATE OR REPLACE PROCEDURE PHOTOGRAPHER_ONE
(
	PID PHOTOGRAPHER.P_ID%TYPE,
	RES OUT SYS_REFCURSOR
)
IS
BEGIN
	OPEN RES FOR SELECT * FROM PHOTOGRAPHER WHERE P_ID = PID;
END PHOTOGRAPHER_ONE;
/

CREATE OR REPLACE PROCEDURE UPDATE_PHOTOGRAPHER
(
	PID PHOTOGRAPHER.P_ID%TYPE,
	CAM PHOTOGRAPHER.CAMERA%TYPE,
	CON PHOTOGRAPHER.CONCEPT%TYPE,
	CR PHOTOGRAPHER.CAREER%TYPE,
	UL PHOTOGRAPHER.URL%TYPE
)


	UPDATE PHOTOGRAPHER SET CAMERA=CAM, CONCEPT=CON, CAREER=CR, URL=UL WHERE P_ID=PID;
COMMIT;
END UPDATE_PHOTOGRAPHER;
/


	
CREATE OR REPLACE PROCEDURE FINDPROFILE
(
	PID IN PICTURE.P_ID%TYPE,
	FNAME OUT PICTURE.FILE_NAME%TYPE
)
IS
BEGIN
	SELECT FILE_NAME INTO FNAME FROM PICTURE WHERE P_ID = PID;
END FINDPROFILE;
/

CREATE OR REPLACE PROCEDURE M_IDCHECK
(
	MID MODEL.M_ID%TYPE,
	RES OUT NUMBER
)
IS
BEGIN
	SELECT COUNT(*) INTO RES FROM MODEL WHERE M_ID = MID;
END M_IDCHECK;
/


CREATE OR REPLACE PROCEDURE P_IDCHECK
(
	PID PHOTOGRAPHER.P_ID%TYPE,
	RES OUT NUMBER
)
IS
BEGIN
	SELECT COUNT(*)  INTO RES FROM PHOTOGRAPHER WHERE P_ID = PID;
END P_IDCHECK;
/

CREATE OR REPLACE PROCEDURE P_SEARCH_BOARD
(
	S_DAY NOTICE_BOARD.DAY%TYPE,
	S_MAX NOTICE_BOARD.MAX%TYPE,
	S_CONCEPT NOTICE_BOARD.CONCEPT%TYPE,
	RES OUT SYS_REFCURSOR
)
IS
BEGIN
	OPEN RES FOR SELECT * from notice_board where day<s_day and max = S_MAX and concept=S_CONCEPT  ;
END P_SEARCH_BOARD;
/

