drop sequence MODEL_SEQ;
drop sequence PHOTOG_SEQ;
drop sequence PIC_SEQ;
drop sequence REV_SEQ;
drop sequence CAMERA_SEQ;
drop sequence BRD_SEQ;



CREATE SEQUENCE MODEL_SEQ
INCREMENT BY 1
START WITH 1;
CREATE SEQUENCE PHOTOG_SEQ
INCREMENT BY 1
START WITH 1;
CREATE SEQUENCE PIC_SEQ
INCREMENT BY 1
START WITH 1;
CREATE SEQUENCE REV_SEQ
INCREMENT BY 1
START WITH 1;
CREATE SEQUENCE CAMERA_SEQ
INCREMENT BY 1
START WITH 1;
CREATE SEQUENCE BRD_SEQ
INCREMENT BY 1
START WITH 1;
