DROP TABLE CAMERA CASCADE CONSTRAINT;
CREATE TABLE CAMERA (
	CAMERA_SEQ NUMBER,
	MAKER VARCHAR2(30) NOT NULL,
	CAMERA_TYPE NUMBER NOT NULL,
	PIXEL NUMBER DEFAULT 0 NOT NULL ,
	CONSTRAINT CAMERA_PK PRIMARY KEY (CAMERA_SEQ)
);

DROP TABLE MODEL CASCADE CONSTRAINT;
CREATE TABLE MODEL (
	MODEL_SEQ NUMBER,
	M_ID VARCHAR2(30) NOT NULL,
	M_PASSWORD VARCHAR2(20) NOT NULL,
	M_NAME VARCHAR2(30) NOT NULL,
	M_GENDER VARCHAR2(10),
	M_BDAY DATE,
	M_KA_ID VARCHAR2(30) NOT NULL,
	CONSTRAINT MODEL_PK PRIMARY KEY (MODEL_SEQ),
	CONSTRAINT MODEL_MID_UNIQUE UNIQUE (M_ID),
	CONSTRAINT MODEL_GENDER_CK CHECK (M_GENDER IN ('M','F'))
);

DROP TABLE PHOTOGRAPHER CASCADE CONSTRAINT;
CREATE TABLE PHOTOGRAPHER (
	PHOTOG_SEQ NUMBER,
	P_ID VARCHAR2(30) NOT NULL,
	P_PASSWORD VARCHAR2(20) NOT NULL,
	P_NAME VARCHAR2(30) NOT NULL,
	P_GENDER VARCHAR2(10),
	P_BDAY DATE,
	P_KA_ID VARCHAR2(30) NOT NULL,
	CAMERA_SEQ NUMBER NOT NULL,
	CONCEPT NUMBER NOT NULL,
	CAREER VARCHAR2(200),
	URL VARCHAR2(200),
	CONSTRAINT PHOTOGRAPHER_PK PRIMARY KEY (PHOTOG_SEQ),
	CONSTRAINT PHOTOGRAPHER_FK FOREIGN KEY (CAMERA_SEQ) REFERENCES CAMERA (CAMERA_SEQ),
	CONSTRAINT PHOTOGRAPHER_PID_UNIQUE UNIQUE (P_ID),
	CONSTRAINT PHOTOGRAPHER_GENDER_CK CHECK (P_GENDER IN ('M','F')),
	CONSTRAINT PHOTOGRAPHER_CONCEPT_CK CHECK (CONCEPT IN (0, 1, 2, 3))
);

DROP TABLE NOTICE_BOARD CASCADE CONSTRAINT;
CREATE TABLE NOTICE_BOARD (
	BRD_SEQ NUMBER,
	P_ID VARCHAR2(30) NOT NULL,
              START_TIME VARCHAR2(20) NOT NULL,
	END_TIME VARCHAR2(20) NOT NULL,
	PLACE VARCHAR2(50) NOT NULL,
	CONCEPT NUMBER DEFAULT 0 NOT NULL ,
	MAX NUMBER  DEFAULT 1 NOT NULL ,
	PROGRESS NUMBER DEFAULT 0 NOT NULL ,
	 DAY DATE NOT NULL,
	TITLE VARCHAR2(50),
	CONTENT VARCHAR2(200),
	CONSTRAINT BOARD_PK PRIMARY KEY (BRD_SEQ),
	CONSTRAINT BOARD_PID_FK FOREIGN KEY (P_ID) REFERENCES PHOTOGRAPHER (P_ID),
	CONSTRAINT BOARD_CONCEPT_CK CHECK (CONCEPT IN (0, 1, 2, 3)),
	CONSTRAINT BOARD_PROGRESS_CK CHECK (PROGRESS IN (0, 1))
);





DROP TABLE PICTURE CASCADE CONSTRAINT;
CREATE TABLE PICTURE (
	PIC_SEQ NUMBER,
              P_ID VARCHAR2(30) NOT NULL,
	FILE_PATH VARCHAR2(200) NOT NULL,
	FILE_NAME VARCHAR2(200) NOT NULL,
	CONSTRAINT PIC_PK PRIMARY KEY (PIC_SEQ),
	CONSTRAINT PIC_PID_FK FOREIGN KEY (P_ID) REFERENCES PHOTOGRAPHER (P_ID)
);

DROP TABLE RESERVATION CASCADE CONSTRAINT;
CREATE TABLE RESERVATION (
		REV_SEQ NUMBER,
		BRD_SEQ NUMBER NOT NULL,
		M_ID VARCHAR2(30) NOT NULL,
		CONCEPT NUMBER NOT NULL,
		PEOPLE_NUM NUMBER NOT NULL,
		START_TIME VARCHAR2(20) NOT NULL,
		END_TIME VARCHAR2(20) NOT NULL,
		PROGRESS NUMBER DEFAULT 0 NOT NULL ,
                             DAY DATE NOT NULL,
		CONSTRAINT RESERV_PK PRIMARY KEY (REV_SEQ),
		CONSTRAINT RESERV_BRD_SEQ_FK FOREIGN KEY (BRD_SEQ) REFERENCES NOTICE_BOARD (BRD_SEQ),
		CONSTRAINT RESERV_MID_FK FOREIGN KEY (M_ID) REFERENCES MODEL (M_ID),
		CONSTRAINT RESERV_CONCEPT_CK CHECK (CONCEPT IN (0, 1, 2, 3))
);

DROP TABLE ADMINISTRATOR CASCADE CONSTRAINT;
CREATE TABLE ADMINISTRATOR (
		ID VARCHAR2(30),
		PASSWORD VARCHAR2(30) NOT NULL,
		CONSTRAINT ADMIN_PK PRIMARY KEY (ID)
);

DROP TABLE MAP CASCADE CONSTRAINT;
CREATE TABLE MAP (
		MAP_SEQ NUMBER,
		LAT NUMBER NOT NULL,
		LON NUMBER NOT NULL,
		PATH VARCHAR2(200) NOT NULL,
		P_ID VARCHAR2(30) NOT NULL,
		CONSTRAINT MAP_PK PRIMARY KEY (MAP_SEQ),
CONSTRAINT MAP_FK FOREIGN KEY (P_ID) REFERENCES PHOTOGRAPHER (P_ID)
);
