CREATE OR REPLACE TRIGGER BOARD_DELETE
AFTER DELETE ON NOTICE_BOARD FOR EACH ROW
BEGIN
DELETE FROM RESERVATION WHERE RESERVATION.BRD_SEQ = :OLD.BRD_SEQ;
END BOARD_DELETE;
/

CREATE OR REPLACE TRIGGER MODEL_DELETE
AFTER DELETE ON MODEL FOR EACH ROW
BEGIN
DELETE FROM RESERVATION WHERE RESERVATION.M_ID = :OLD.M_ID;
END MODEL_DELETE;
/

CREATE OR REPLACE TRIGGER PHOTOGRAPHER_DELETE
AFTER DELETE ON PHOTOGRAPHER FOR EACH ROW 
BEGIN
DELETE FROM PICTURE WHERE PICTURE.P_ID = :OLD.P_ID; 
DELETE FROM NOTICE_BOARD WHERE NOTICE_BOARD.P_ID = :OLD.P_ID;
END PHOTOGRAPHER_DELETE;
/

CREATE OR REPLACE TRIGGER UPDATE_PROGRESS
AFTER UPDATE ON RESERVATION FOR EACH ROW
BEGIN
UPDATE NOTICE_BOARD SET PROGRESS = 1 WHERE NOTICE_BOARD.BRD_SEQ = :OLD.BRD_SEQ;
END UPDATE_PROGRESS;
/
